# Generated by Django 6.0.2 on 2026-03-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent Full Name')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent Email Address')),
                ('student_age', models.IntegerField(verbose_name='Student Age')),
                ('coding_experience', models.CharField(choices=[('1', 'No experience'), ('2', 'Some beginner exposure'), ('3', 'Completed a coding course before')], max_length=1, verbose_name='Has your child had any prior coding experience?')),
                ('main_goal', models.TextField(verbose_name='What is your main goal for enrolling your child in this program?')),
                ('consideration_range', models.CharField(choices=[('1', 'Yes'), ('2', 'I’d like to discuss further')], max_length=1, verbose_name='This is a structured 12-week private mentorship with an investment of $2400 total. Is this within your consideration range if it’s a strong fit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
